# Generated by Django 4.2.7 on 2023-11-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_remove_category_sub_category_remove_orders_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
