# Generated by Django 4.2.7 on 2023-12-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_remove_post_image_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Đang chờ xử lý', 'Đang chờ xử lý'), ('Xác nhận đặt hàng', 'Xác nhận đặt hàng'), ('Đang giao hàng', 'Đang giao hàng'), ('Đã giao hàng', 'Đã giao hàng')], max_length=50, null=True),
        ),
    ]
