# Generated by Django 4.2.7 on 2024-01-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
