# Generated by Django 4.2.7 on 2024-01-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_alter_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
