# Generated by Django 4.2.7 on 2024-01-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_alter_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
