# Generated by Django 4.2.7 on 2024-01-31 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_alter_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
